services:
  code: 
    image: nodecode
    ports: 
      - 8080:8080
    command:
      - /bin/sh
      - -c
      - |
        git clone https://github.com/yellowmachine/reactjs-demo.git .
        code-server /project
