services:
  ika:
    image: yellowmachine/icarus
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_MODE=$MODE
        - PASSWORD=$PASSWORD
        - JWT_SECRET=$JWT_SECRET
        - PUBLIC_DOMAIN=$DOMAIN
    ports:
      - 3000:3000
    environment:
      - ORIGIN=localhost
      - MODE=port
      - PASSWORD=secret
      - JWT_SECRET=secret
      - DOMAIN=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/../server/workspaces:/workspaces
  