services:
  code: 
    image: codenode
    ports: 
      - $A:8080
      - $B:5173
    command:
      - /bin/sh
      - -c
      - |
        yes | npx degit https://github.com/yellowmachine/kit-uno-stories-trpc.git .
        code-server /project
