services:
  db:
    image: dgraph/standalone:master
  code:
    image: codenode 
    ports: 
      - 8080:8080
      - 5173:5173
    command:
      - /bin/sh
      - -c
      - |
        git clone https://github.com/yellowmachine/ika-example-dgraph.git .
        code-server /project
