version: "3"

services:
  db:
    image: dgraph/standalone:master
  code: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_KEY=$SSH_KEY
    ports: 
      - 8080:8080
      - 5173:5173
    environment:
      - SSH_KEY=$SSH_KEY
    command:
      - /bin/sh
      - -c
      - |
        git clone https://github.com/yellowmachine/ika-example-dgraph.git .
        code-server /project
